[package]
name = "tms2xyz"
version = "0.1.0"
authors = ["Samuel J Vanderwaal <samuel.vanderwaal@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
walkdir = "2.3.1"
regex = "1.3.4"
lazy_static = "1.4.0"
failure = "0.1.6"
jwalk = "0.4.0"
